### ISSUE TITLE
Links to .md files get converted to .html

### ISSUE THREAD

**Issue by klamping** [bryanbraun/franklin#1]
I have a link in my code to a .md file on github, but when rendered, it points to .html instead. 

For example:
`[the full tests documentation](https://github.com/bem/gemini/blob/master/doc/tests.md)`

gets converted to:
`<a href="https://github.com/bem/gemini/blob/master/doc/tests.html">the full tests documentation</a>`

There is a workaround for this, which is to add a `#` at the end of the url: `[the full tests documentation](https://github.com/bem/gemini/blob/master/doc/tests.md#)`. Doing that preserves the link.

**Comment by bryanbraun** [comment]
Good catch. This is happening as part of a separate Bitbooks gem that deploys a generated site to Github pages. It's supposed to only change the extensions for internal links... ensuring that links pointing to `.md` within your own repo will point to the correct `.html` file once the site is generated. This is the regex: `regex = /(?:href=")(?:.*)(.md|.markdown)(?:")/`. Clearly, it's too broad.

That code isn't a part of this repo, so it won't be an issue for people using Franklin outside of Bitbooks.
