### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by rovo79** [bryanbraun/franklin#7]
Is there a screenshot available to get a visual idea of what this generates?

**Comment by bryanbraun** [comment]
@rovo79,

Here are a few example books, one using each theme that comes with Franklin:
- http://bitbooks.github.io/example-book-epsilon/
- http://bitbooks.github.io/example-book-glide/
- http://bitbooks.github.io/example-book-hamilton/

You're right, we should probably add these links (and a screenshot) to the readme.

**Comment by rovo79** [comment]
Hey Bryan,
These look awesome. Thanks for sharing.

**Comment by psiinon** [comment]
+1 for adding these to the readme - I was going to skip this project due to the lack of examples until I noticed them in this issue.
